name: Deploy Docker Image to EC2

on:
  push:
    branches:
      - main

env:
  EC2_USER: ec2-user                        # Update with your EC2 username
  EC2_HOST: ${{ secrets.EC2_HOST }}          # EC2 Public IP/Hostname (add to GitHub Secrets)
  EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}        # Private SSH Key (add to GitHub Secrets)
  TARGET_PORT: 8080                          # Port on which the application will run

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Build the JAR file using Maven
      - name: Build JAR file with Maven
        run: |
          mvn clean package -DskipTests

      # 4. Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      # 5. Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t demo-app:latest .

      # 6. Save the Docker image as a tar file
      - name: Save Docker image to tar
        run: |
          docker save -o demo-app.tar demo-app:latest

      # 7. Upload the image to EC2 via SCP
      - name: Copy Docker image to EC2
        run: |
          echo "${EC2_SSH_KEY}" > ec2_key.pem
          chmod 600 ec2_key.pem
          scp -o StrictHostKeyChecking=no -i ec2_key.pem demo-app.tar $EC2_USER@$EC2_HOST:/root/u003/

      # 8. Load and Run Docker container on EC2
      - name: Load and run Docker container on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem $EC2_USER@$EC2_HOST << 'EOF'
          sudo docker load -i /tmp/demo-app.tar
          sudo docker stop demo-container || true
          sudo docker rm demo-container || true
          sudo docker run -d -p 8080:8080 --name demo-container demo-app:latest
          EOF

      # 9. Test application availability (Optional)
      - name: Test application availability
        run: |
          curl -I http://$EC2_HOST:8080
